sudo: false
language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  sauce_connect:
   username: wordofchristian
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  jwt:
    secure: jEDkGrQ7IFmHTxQJ8MJ1gH+DmkH8XFzIZHtHN1wMyxS7YMn/oP0JtNsJg10c+WZc9v3mtGDDI7ETrT6cw4HHR1qJ9/mxCT79jf30U5gjisUe3JOayVJQaVIVCFHw7e8L3+2b7Co1aZJF38JlJLfYTr9gvWcJPniDJyxFTf7/zzQ=
before_install:
- npm install -g grunt-cli
script: karma start --single-run
