sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
before_install:
  - npm i -g npm@5.3.0
  - npm i -g lerna
  - gem install bundler -v 1.16.1
install:
  - BUNDLE_GEMFILE="packages/browser/Gemfile" bundle install
  - npm install
  - lerna bootstrap
before_script:
  - lerna run build  --scope='@bugsnag/browser'
script:
  - npm run test:browser
env:
  global:
    - BROWSER_STACK_USERNAME: bugsnagplatforms1
    - secure: "ft2MvNmJ3U2frZEf6x3isWBg46cS1ofZ3np+ABE+5ehF1GztMk44DFasdQSwp5FQGbpJkHWmr0q9l90mCT579yDYA3ZzeUaMykz8Y5dmfFM1bbn6Qe8atOs1MG0AZUDIK+lZmgdwhXhZ4URU3fYt6bguHeK2thYkpp0dnOECrhM="
  matrix:
    - BROWSER=ie_8
    - BROWSER=ie_9
    - BROWSER=ie_10
    - BROWSER=ie_11
    - BROWSER=edge_14
    - BROWSER=edge_15
    - BROWSER=safari_6
    - BROWSER=safari_10
    - BROWSER=opera_12
    - BROWSER=iphone_7
    - BROWSER=android_s8
    - BROWSER=firefox_30
    - BROWSER=firefox_56
    - BROWSER=chrome_43
    - BROWSER=chrome_61
addons:
  browserstack:
    username: bugsnagplatforms1
    access_key:
      secure: "ePNnHg5KPmMsyHa98Wy70Pkariv+b8qCh6UXEz2sFLXVNh2J0FYiqDgkfnp9j+IYYHy1Il4JCsK7+ZaCAbr1qQr5pkLepTMJlIiecA7DVrcwl4Ho4Lk/rjU1umpECcxqh4COd62KGg1JirQDXR+TtmdcQZgNhlg4VUXKEvfDOmo="

stage: browser end to end tests

jobs:
  include:
    - stage: linting
      install:
        - npm install
        - lerna bootstrap
      script: npm run test:lint
      env: BROWSER=na
    - stage: unit tests
      install:
        - npm install
        - lerna bootstrap
        - lerna run build
      script:
        - npm run test:unit && npm run test:types
      env: BROWSER=na
    - stage: node end to end tests
      install:
        - BUNDLE_GEMFILE="packages/node/Gemfile" bundle install
        - npm install
        - lerna bootstrap
        - lerna run build --scope='@bugsnag/node' --scope='@bugsnag/plugin-express' --scope='@bugsnag/plugin-koa' --scope='@bugsnag/plugin-restify'
      script:
        - npm run test:node
      env: BROWSER=na

stages:
  - linting
  - unit tests
  - node end to end tests
  - browser end to end tests
