version: '3.5'
services:
  ci:
    build: ./

  node-maze-runner:
    build:
      context: .
      target: node-maze-runner
    command: /app/features/connect.feature
    networks:
      - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  maze-runner:
    name: maze-runner