version: '3.4'
services:
  ci-basic:
    build:
      context: .
      dockerfile: Dockerfile.ci-basic

  ci-browser:
    build:
      context: .
      dockerfile: Dockerfile.ci-browser
    environment:
      - BROWSER_STACK_USERNAME
      - BROWSER_STACK_ACCESS_KEY
      - BROWSER
      - CI
    command: bundle exec maze-runner features/auto_notify
