version: '3.5'
services:
  ci:
    build:
      context: .
      target: ci

  browser-maze-runner:
    build:
      context: .
      target: browser-maze-runner
    networks:
      - maze-runner
    environment:
      - BROWSER
      - BROWSER_STACK_USERNAME
      - BROWSER_STACK_ACCESS_KEY

  node-maze-runner:
    build:
      context: .
      target: node-maze-runner
    command: /app/features/connect.feature
    networks:
      - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  maze-runner:
    name: maze-runner
