version: '3.6'
services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci

  browser-maze-runner:
    build:
      context: .
      dockerfile: Dockerfile.browser
      target: browser-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      - BROWSER
      - BROWSER_STACK_USERNAME
      - BROWSER_STACK_ACCESS_KEY

  node-maze-runner:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: node-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    command: features/connect.feature
    container_name: maze-runner
    environment:
      NODE_VERSION:
      VERBOSE: 'true'
    networks:
      node-maze-runner:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  node-maze-runner:
