version: '3.5'
services:
  ci:
    build:
      context: .
      target: ci

  browser-maze-runner:
    build:
      context: .
      target: browser-maze-runner
    networks:
      - maze-runner
    environment:
      - BROWSER
      - BROWSER_STACK_USERNAME
      - BROWSER_STACK_ACCESS_KEY

  node-maze-runner:
    build:
      context: .
      target: node-maze-runner
    environment:
      NODE_VERSION:
    networks:
      node-maze-runner:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  node-maze-runner:
    name: node-v${NODE_VERSION:-10}-maze-runner
  maze-runner:
    name: maze-runner
