version: '3.6'
services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci

  browser-maze-runner:
    build:
      context: .
      dockerfile: Dockerfile.browser
      target: browser-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    networks:
      - maze-runner
    environment:
      - BROWSER
      - BROWSER_STACK_USERNAME
      - BROWSER_STACK_ACCESS_KEY

  node-maze-runner:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: node-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      NODE_VERSION:
    networks:
      node-maze-runner:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  node-maze-runner:
    name: node-v${NODE_VERSION:-10}-maze-runner
  maze-runner:
