steps:
  - label: 'Build'
    plugins:
      docker-compose#v2.5.1:
        build: ci-basic
      ecr#v1.1.4:
        login: true

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
      ecr#v1.1.4:
        login: true
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
      ecr#v1.1.4:
        login: true
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
      ecr#v1.1.4:
        login: true
    command: 'npm run test:types'

  - wait

  - label: 'Browser tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-browser
    env:
      BROWSER: "chrome_61"
