steps:
  - label: ':docker: Build'
    plugins:
      docker-compose#v2.5.1:
        build: ci-basic
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
        cache-from: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js:latest

  - label: ":docker: Push latest to repository"
    plugins:
      docker-compose#v2.5.1:
        push:
          - 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          - 855461928731.dkr.ecr.us-west-1.amazonaws.com/js:latest

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:types'

  # - wait

  # - label: 'Browser tests'
  #   plugins:
  #     docker-compose#v2.5.1:
  #       run: ci-browser
  #   env:
  #     BROWSER: "chrome_61"
