steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest
      - docker-compose#v2.6.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:types'

  - label:  ':docker: Build browser maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - browser-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - label:  ':docker: Build node maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - node-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - label: ':docker: Build expo maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - expo-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
      - docker-compose#v2.6.0:
          push:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - wait

  # - label: ':chrome: v43 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "chrome_43"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':chrome: v61 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "chrome_61"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':ie: v8 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "ie_8"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':ie: v9 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "ie_9"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':ie: v10 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "ie_10"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':ie: v11 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "ie_11"
  #     HOST: 'localhost' # IE11 needs the host set to localhost for some reason!ß
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':edge: v14 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "edge_14"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':edge: v15 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "edge_15"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':safari: v6 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "safari_6"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':safari: v10 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "safari_10"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':desktop_computer: Opera v12 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "opera_12"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':iphone: iOS 10.3 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "iphone_7"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':android: Samsung Galaxy S8 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "android_s8"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':firefox: v30 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "firefox_30"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':firefox: v56 Browser tests'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: browser-maze-runner
  #       use-aliases: true
  #   env:
  #     BROWSER: "firefox_56"
  #   concurrency: 5
  #   concurrency_group: 'browserstack'

  # - label: ':node: Node 4'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: node-maze-runner
  #       use-aliases: true
  #   env:
  #     NODE_VERSION: "4"
  #   command: '-e koa.feature -e koa-1x.feature -e webpack.feature'

  # - label: ':node: Node 6'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: node-maze-runner
  #       use-aliases: true
  #   env:
  #     NODE_VERSION: "6"
  #   command: '-e koa.feature -e koa-1x.feature'

  # - label: ':node: Node 8'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: node-maze-runner
  #       use-aliases: true
  #   env:
  #     NODE_VERSION: "8"

  # - label: ':node: Node 10'
  #   plugins:
  #     docker-compose#v2.6.0:
  #       run: node-maze-runner
  #       use-aliases: true
  #   env:
  #     NODE_VERSION: "10"

  - label: ':docker: Publish expo app'
    plugins:
      - docker-compose#v2.6.0:
          run: expo-publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - wait

  - label: ':docker: Build expo APK'
    artifact_paths: build/output.apk
    plugins:
      - docker-compose#v2.6.0:
          run: expo-android-builder
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - label: ':docker: Build expo IPA'
    agents:
      queue: "opensource-mac"
    artifact_paths: build/output.ipa
    commands:
      - cd test/expo/features/fixtures/test-app
      - npm i turtle-cli
      - |
        perl -0777 -i.original -pe "s/entitlements\\['aps-environment'\\] =[^;]+;//gs" node_modules/turtle-cli/node_modules/xdl/build/detach/IosNSBundle.js
      - mkdir build
      - |
        node_modules/.bin/turtle build:ios --team-id $APPLE_TEAM_ID --dist-p12-path $$EXPO_P12_PATH --provisioning-profile-path $$EXPO_PROVISIONING_PROFILE_PATH -o build/output.ipa

  - wait

  - label: 'expo Android 9'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_9"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo Android 8'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_8"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo Android 7'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_7"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo Android 6'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_6"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo Android 5'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_5"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo iOS 10'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_10"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo iOS 11'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_11"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack'

  - label: 'expo iOS 12'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_12"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack'