steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v2.5.1:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest
      - docker-compose#v2.5.1:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest
            # This image is used as the FROM in the maze runner images built after this one
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BUILD_NUMBER}

  - wait

  # - label:  ':docker: Build browser maze runner image'
  #   plugins:
  #     # Required for multiple cache from images for a single service
  #     - bugsnag/docker-compose#v2.5.3:
  #         build:
  #           - browser-maze-runner
  #         image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
  #         cache-from:
  #           - browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:browser-maze-runner-${BUILDKITE_BRANCH}
  #           - browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:browser-maze-runner-latest
  #     - docker-compose#v2.5.1:
  #         push:
  #           - browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:browser-maze-runner-${BUILDKITE_BRANCH}
  #           - browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:browser-maze-runner-latest

  - label:  ':docker: Build node maze runner image'
    plugins:
      # Required for multiple cache from images for a single service
      - bugsnag/docker-compose#v2.5.3:
          build:
            - node-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:node-maze-runner-${BUILDKITE_BRANCH}
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:node-maze-runner-latest
      - docker-compose#v2.5.1:
          push:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:node-maze-runner-${BUILDKITE_BRANCH}
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:node-maze-runner-latest

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'npm run test:types'

  - wait

  # - label: ':chrome: Browser tests'
  #   plugins:
  #     docker-compose#v2.5.1:
  #       run: browser-maze-runner
  #   env:
  #     BROWSER: "chrome_61"

  - label: ':node: Node 4'
    plugins:
      # Required for use-aliases support
      bugsnag/docker-compose#v2.5.3:
        run: node-maze-runner
        use-aliases: true
    env:
      COMPOSE_PROJECT_NAME: node4
      NODE_VERSION: "4"
    command: '-e koa.feature -e koa-1x.feature'

  - label: ':node: Node 6'
    plugins:
      # Required for use-aliases support
      bugsnag/docker-compose#v2.5.3:
        run: node-maze-runner
        use-aliases: true
    env:
      COMPOSE_PROJECT_NAME: node6
      NODE_VERSION: "6"
    command: '-e koa.feature -e koa-1x.feature'

  - label: ':node: Node 8'
    plugins:
      # Required for use-aliases support
      bugsnag/docker-compose#v2.5.3:
        run: node-maze-runner
        use-aliases: true
    env:
      COMPOSE_PROJECT_NAME: node8
      NODE_VERSION: "8"

  - label: ':node: Node 10'
    plugins:
      # Required for use-aliases support
      bugsnag/docker-compose#v2.5.3:
        run: node-maze-runner
        use-aliases: true
    env:
      COMPOSE_PROJECT_NAME: node10
      NODE_VERSION: "10"
