plugins: &plugins
  docker-compose#v2.5.1:
    run: ci

steps:
  - label: 'Lint'
    plugins: *plugins
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins: *plugins
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins: *plugins
    command: 'npm run test:types'

  - wait

  - label: 'Browser tests'
    plugins:
      docker-compose#v2.5.1:
        run: browser-maze-runner
    command: 'bundle exec maze-runner'
    env:
      BROWSER: "chrome_61"
