steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v2.5.1:
          build: ci-basic
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from: ci-basic:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:${BUILDKITE_BRANCH:-[latest]}
      - docker-compose#v2.5.1:
          push:
            - ci-basic:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:latest
            - ci-basic:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:${BUILDKITE_BRANCH}

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci-basic
    command: 'npm run test:types'

  - wait

  - label: 'Browser tests'
    plugins:
      docker-compose#v2.5.1:
        run: maze-runner
    env:
      BROWSER: "chrome_61"
