plugins: &plugins
  docker-compose#v2.5.1:
    run: ci

steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v2.5.1:
        build: ci
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
        cache-from: ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:${BUILDKITE_BRANCH:-[latest]}
      - docker-compose#v2.5.1:
        push:
          - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:latest
          - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:${BUILDKITE_BRANCH}

  - label: 'Lint'
    plugins: *plugins
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins: *plugins
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins: *plugins
    command: 'npm run test:types'

  - wait

  - label: 'Browser tests'
    plugins:
      docker-compose#v2.5.1:
        run: browser-maze-runner
    command: 'bundle exec maze-runner'
    env:
      BROWSER: "chrome_61"
