steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest
      - docker-compose#v2.6.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - wait

  - label: 'Lint'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    plugins:
      docker-compose#v2.6.0:
        run: ci
    command: 'npm run test:types'

  - label:  ':docker: Build browser maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - browser-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - label:  ':docker: Build node maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build:
            - node-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}

  - wait

  - label: ':chrome: Browser tests'
    plugins:
      docker-compose#v2.6.0:
        run: browser-maze-runner
    env:
      BROWSER: "chrome_61"

  - label: ':node: Node 4'
    plugins:
      docker-compose#v2.6.0:
        run: node-maze-runner
        use-aliases: true
    env:
      NODE_VERSION: "4"
    command: '-e koa.feature -e koa-1x.feature -e webpack.feature'

  - label: ':node: Node 6'
    plugins:
      docker-compose#v2.6.0:
        run: node-maze-runner
        use-aliases: true
    env:
      NODE_VERSION: "6"
    command: '-e koa.feature -e koa-1x.feature'

  - label: ':node: Node 8'
    plugins:
      docker-compose#v2.6.0:
        run: node-maze-runner
        use-aliases: true
    env:
      NODE_VERSION: "8"

  - label: ':node: Node 10'
    plugins:
      docker-compose#v2.6.0:
        run: node-maze-runner
        use-aliases: true
    env:
      NODE_VERSION: "10"
